name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  percent_indicator: ^4.2.3
  fl_chart: ^1.1.0
  logger: ^2.0.2+1
  firebase_core: ^2.30.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.5
  youtube_player_flutter: ^9.0.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
